const pastryChoice = [
	{
		id: 1,
		name: "Cinnamon Snail",
		primaryFlavour: "Cinnamon",
		countryOfOrigin: "Denmark",
		priceGBP: 2.5,
	},
	{
		id: 2,
		name: "Croissant",
		primaryFlavour: "Buttery",
		countryOfOrigin: "France",
		priceGBP: 1.8,
	},
	{
		id: 3,
		name: "Eccles Cake",
		primaryFlavour: "Currant-filled",
		countryOfOrigin: "United Kingdom",
		priceGBP: 1.7,
	},
	{
		id: 4,
		name: "Cannoli",
		primaryFlavour: "Sweet ricotta cheese",
		countryOfOrigin: "Italy",
		priceGBP: 2.2,
	},
	{
		id: 5,
		name: "Baklava",
		primaryFlavour: "Honey and nuts",
		countryOfOrigin: "Turkey",
		priceGBP: 2.3,
	},
	{
		id: 6,
		name: "Pain au Chocolat",
		primaryFlavour: "Chocolate",
		countryOfOrigin: "France",
		priceGBP: 2.0,
	},
	{
		id: 7,
		name: "Stollen",
		primaryFlavour: "Fruit and marzipan",
		countryOfOrigin: "Germany",
		priceGBP: 3.0,
	},
	{
		id: 8,
		name: "Pastel de Nata",
		primaryFlavour: "Custard",
		countryOfOrigin: "Portugal",
		priceGBP: 1.6,
	},
	{
		id: 9,
		name: "Sachertorte",
		primaryFlavour: "Chocolate and apricot",
		countryOfOrigin: "Austria",
		priceGBP: 4.0,
	},
	{
		id: 10,
		name: "Madeleine",
		primaryFlavour: "Lemon",
		countryOfOrigin: "France",
		priceGBP: 1.2,
	},
	{
		id: 11,
		name: "Sticky Toffee Pudding",
		primaryFlavour: "Date and toffee",
		countryOfOrigin: "United Kingdom",
		priceGBP: 3.5,
	},
	{
		id: 12,
		name: "Churros",
		primaryFlavour: "Cinnamon and sugar",
		countryOfOrigin: "Spain",
		priceGBP: 2.4,
	},
];

module.exports = pastryChoice;
